// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtlTaIh0hPy-1m13NdULG9NCW9Z8Ko1Ps',
    appId: '1:849352728921:web:9e5c00a88cecdf4b4dec48',
    messagingSenderId: '849352728921',
    projectId: 'masakini-ba32a',
    authDomain: 'masakini-ba32a.firebaseapp.com',
    storageBucket: 'masakini-ba32a.firebasestorage.app',
    measurementId: 'G-PZ7090CZJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk5XsupcFLkUQz640PVfvVreVo6ydegl8',
    appId: '1:849352728921:android:4c1ee40a182b10b74dec48',
    messagingSenderId: '849352728921',
    projectId: 'masakini-ba32a',
    storageBucket: 'masakini-ba32a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4IvRLdi3cZuOK3FkXkdN8XXo1lifmK1I',
    appId: '1:849352728921:ios:47071a6c447453dc4dec48',
    messagingSenderId: '849352728921',
    projectId: 'masakini-ba32a',
    storageBucket: 'masakini-ba32a.firebasestorage.app',
    iosBundleId: 'com.example.masakini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4IvRLdi3cZuOK3FkXkdN8XXo1lifmK1I',
    appId: '1:849352728921:ios:47071a6c447453dc4dec48',
    messagingSenderId: '849352728921',
    projectId: 'masakini-ba32a',
    storageBucket: 'masakini-ba32a.firebasestorage.app',
    iosBundleId: 'com.example.masakini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtlTaIh0hPy-1m13NdULG9NCW9Z8Ko1Ps',
    appId: '1:849352728921:web:5bc715735314b6994dec48',
    messagingSenderId: '849352728921',
    projectId: 'masakini-ba32a',
    authDomain: 'masakini-ba32a.firebaseapp.com',
    storageBucket: 'masakini-ba32a.firebasestorage.app',
    measurementId: 'G-S3ZL0XPNW7',
  );

}